### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by sils** [coala-analyzer/coala-design#1]
Let's discuss mockupping for HTML output and GUI here :)

**Comment by shivanipods** [comment]
I have a little WIP, which I designed, after talking to @Udayan12167 . Its very rough and would probably help us to progress further in terms of adding new stuff to the current initial mockup, moving around UI elements, and so on. Once we have a fair idea about what to achieve, me or @Udayan12167 could get this done in collaboration with the gnome-design team (an in a neater place like inkscape).

![coala](https://cloud.githubusercontent.com/assets/2330579/6657192/5bf80ec8-cb69-11e4-98dd-10904ecb5f38.jpg)

**Comment by sils** [comment]
Ok, a bit of feedback like you asked, just a few thoughts:

## Differences

First it's important to highlight the differences between HTML output and GUI. The former presents results, the latter allows the user to influence the configuration and the run. In your mockups it looks like users could invoke coala via the website which probably will not be possible (yet? I think it's out of scope and doesn't make much sense for continuous).

## Feedback

First off, coala is written with a small c. Maybe I should mention that explicitly in the readme or so... you dislike it? File a bug. I like it :)

I like the idea of presenting the user with the list of sections that was executed when he enters the website or part of the gui showing the results of a run. In that mockup it doesn't look that GNOMEy yet but I'm sure you'll figure that out.

If the user now clicks on a section I'd show him the results for it and slide the sections to a sidebar on the left. (Or maybe tabs on top?)

Now when we want to show the user the results we'll want to have some "general" page which shows a list of results that are not associated to a file. We furthermore want to have pages for each file where we got results. I'm not sure if we want to have a sidebar or tabs for those "pages".

The results itself would be similar to the comments in github review showing where it comes from, what severity it is and maybe providing a patch for download or in case of the gui a one-click button for applying it automatically. (And then update the file on the GUI immediately :) We have a filedict so that should be easy.)
