### ISSUE TITLE
Create an artwork for 404 page for coala.io website  

### ISSUE THREAD

**Issue by manu-chroma** [coala-analyzer/coala-design#26]

**Comment by jayvdb** [comment]
i.e. https://coala.io/404 

https://coala.io/ is currently built from https://github.com/coala/landing-frontend

Note this is not a 'create a 404 page' task, but create artwork for a 404 page.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [6199994110443520](https://codein.withgoogle.com/dashboard/tasks/6199994110443520).
