### ISSUE TITLE
HTML Interactor Mockup

### ISSUE THREAD

**Issue by shivanipods** [coala-analyzer/coala-design#3]
The below mockup suggests the user side functionalities which the HTML Interctor Application, sought to be implemented in coala would achieve:
(The webpage still needs to be adapted into a design which inherits from GNOME design components)
- The django webpage allows the user to browse results and the maybe the config file used.
- It may also allow advanced actions, like:
  - Downloading a patch provided by a bear.
  - Downloading a patch which covers the changes from multiple bears.
- At some point of time, allow searching with respect to time and keywords.

Non goals of the application should not be confused and are as follows:
-  Editing the coafile
-  Editing codefiles/applying patches

![screen shot 2015-03-26 at 6 25 27 am](https://cloud.githubusercontent.com/assets/2330579/6838583/d0762670-d381-11e4-981e-8703a2ead3f0.png)
![screen shot 2015-03-26 at 6 25 14 am](https://cloud.githubusercontent.com/assets/2330579/6838584/d0ef7cdc-d381-11e4-9ba6-de23e97fadb0.png)

**Comment by sils** [comment]
Uhm, in your goals you state that the webpage

> allows the user to browse results

Your mockup seem to allow the user to interact with coala as you have a big "Run Tests coala!" button. I thought we agreed that coala should be run automatically when someone pushes to the repository and the website doesn't have to interact with coala as a simplification?

**Comment by shivanipods** [comment]
Sorry for not being clear.
The user does not interact with coala, but that button was implying that coala _somehow_ has to be run _before_ this application comes into picture. Just in the way that we aren't as such going to create any user profiles, but it just suggests that we might take in few bits about the user. Like I mentioned about, this is not a standard mockup but a mere reflection of the functionalities that might be around.

**Comment by sils** [comment]
old. New concepts are there now.
