### ISSUE TITLE
Logo has no viewbox

### ISSUE THREAD

**Issue by jayvdb** [coala-analyzer/coala-design#34]
The logo in https://github.com/coala/documentation/pull/558 has a viewbox defined as `viewbox="0 0 48 48"` , while the file here in this repo does not have one.

Is there any problem with adding the viewbox to the file in this repository?
Is `viewbox="0 0 48 48"` a suitable value for the file in this repository?

If so, adding it here will make it easier to keep the logos in other repos in sync.

**Comment by Utkarsh1308** [comment]
Can this be assigned to me please
