### ISSUE TITLE
Create vector /text file version of documentation coala-header.png

### ISSUE THREAD

**Issue by jayvdb** [coala-analyzer/coala-design#35]
https://github.com/coala/documentation/blob/master/_static/images/coala-header.png should be imported as-is with commit metadata from https://github.com/coala/documentation/commit/a6661783c9b18595a5e5886c220dd4e036c3cdf6

It is currently used on https://github.com/coala/coala/blob/041333cf353f51c0c3c5be2a595a03220a9f9048/docs/index.rst and https://github.com/coala/coala/blob/041333cf353f51c0c3c5be2a595a03220a9f9048/docs/index.rst
(https://github.com/coala/coala/blob/master/docs/_static/images/coala-header.png is a slightly later commit of the same file)

It combines https://github.com/coala/artwork/blob/master/artwork/logo/coala_color.svg with `coala.io`

We need a text file version of it (i.e. SVG), so it can be used by mobans, due to https://github.com/moremoban/moban/issues/16  
e.g. https://gitlab.com/coala/coala-utils/merge_requests/57 

Also need to document the colors of the text - i.e. a visual style guideline.

**Comment by jayvdb** [comment]
Another possibility is to recreate it using the logo and HTML/CSS.

**Comment by blazeu** [comment]
The font looks like `Roboto Thin` but slightly thicker to me. I think we need to document that too.

**Comment by shikharvaish28** [comment]
I have to import the coala-header.png image by cherry-picking and then convert it into svg format. 

Please correct me if I'm wrong. @jayvdb 

Also, what do you mean by "Also need to document the colors of the text - i.e. a visual style guideline."

**Comment by jayvdb** [comment]
The file has already been imported into this repo in https://github.com/coala/artwork/pull/36

Now we need to deconstruct it so it is a combination of the logo, and the text, with the correct proportions.

The new format could be a vector format which *dynamically* embeds the logo.

Or it could be a .html file (with embedded CSS) or similar which embeds the logo and uses funky CSS to layout the text correctly.

The goal is that we have something which can be used by the docs instead of the .png.

**Comment by shikharvaish28** [comment]
So what I would be doing is:

1.  Create an HTML and CSS file(Using some bootstrap would be fine?)

2. Make the logo responsive(I'll be using the https://github.com/coala/artwork/blob/master/artwork/logo/coala_color.svg file for it)

3. Align the text 'coala.io' next to the responsive logo so that it appears same as the png image.

Upon approval, I'll start working on this.

Sorry for bugging though. I feel it's better to confirm first rather that correcting it everytime :)

**Comment by shikharvaish28** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [coala/artwork](https://trello.com/c/CLsiPpDF/4-coala-artwork)
