### ISSUE TITLE
coala-analyzer.org --> coala.io at artwork/ads/joinus.svg

### ISSUE THREAD

**Issue by ayan-b** [coala-analyzer/coala-design#42]
Change coala-analyzer.org to coala.io: https://github.com/coala/artwork/blob/master/artwork/ads/joinus.svg . A GCI task.

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @fneu, and @sils.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [6555654446645248](https://codein.withgoogle.com/dashboard/tasks/6555654446645248).
