### ISSUE TITLE
coala-analyzer.org --> coala.io at artwork/business_cards/full_card.pdf

### ISSUE THREAD

**Issue by ayan-b** [coala-analyzer/coala-design#43]
Change coala-analyzer.org to coala.io: https://github.com/ayan-b/artwork/blob/master/artwork/business_cards/full_card.pdf . A GCI task.

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jayvdb.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [4863194850918400](https://codein.withgoogle.com/dashboard/tasks/4863194850918400).
