### ISSUE TITLE
Update gitter link at README: coala-analyzer --> coala

### ISSUE THREAD

**Issue by ayan-b** [coala-analyzer/coala-design#44]
A GCI task.

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sils.

**Comment by jayvdb** [comment]
Fixed by https://github.com/coala/artwork/pull/55

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [5471116417040384](https://codein.withgoogle.com/dashboard/tasks/5471116417040384).
