### ISSUE TITLE
Change no of languages to 70+ at artwork/ads/joinus.svg

### ISSUE THREAD

**Issue by ayan-b** [coala-analyzer/coala-design#49]
A GCI task.

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jayvdb.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [5994964988198912](https://codein.withgoogle.com/dashboard/tasks/5994964988198912).
