### ISSUE TITLE
Better version of coala-header

### ISSUE THREAD

**Issue by sangamcse** [coala-analyzer/coala-design#53]
Both `a` in `coala.io` texts of [coala-header](https://github.com/coala/artwork/blob/master/artwork/logo/coala-header.svg) SVG is not rendering perfectly. It looks odd to https://github.com/coala/artwork/blob/master/artwork/logo/coala-header.png.

@ayan-b I have better version made using Inkscape ready at https://github.com/coala/coala/pull/5832 that I will sync in this repo.

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jayvdb.
