### ISSUE TITLE
Separate coala-header text

### ISSUE THREAD

**Issue by sangamcse** [coala-analyzer/coala-design#56]
Good idea to have a separate SVG for`coala.io`'s text.
This issue is to create the text's SVG as per the discussion at https://github.com/coala/artwork/pull/54#issuecomment-431686863

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jayvdb.

**Comment by sangamcse** [comment]
> It would be better to try using https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text for the 'coala.io'

In this case, we can face the font loading problem as we are using `Roboto` by Google and it takes time to load in some browser (One is Firefox in Windows Desktop where I tried opening the header available at https://github.com/sangamcse/artwork/blob/coala-text/artwork/logo/coala_io_text.svg).

Noticing that issue, my proposal is to make the outline of coala.io text.
