### ISSUE TITLE
Design for a blog aggregator

### ISSUE THREAD

**Issue by sils** [coala-analyzer/coala-design#9]
we'll want an own blog agregator for coala related blog posts. Needs design and of course implementation but it shouldn't be too hard to do.

**Comment by sils** [comment]
planet.coala-analyzer.org :)

**Comment by AbdealiLoKo** [comment]
Wordpress/Drupal will have plugins for this. It would be _considerably_
easy to just use a wordpress/drupal theme

**Comment by sils** [comment]
Well then we probably should do that. However I would love to have some
common style across all websites, at least a common background image and
similar alignment or so...

**Comment by sils** [comment]
we have planet.coala-analyzer.org which works, no need for anything more fancy
